<?php

namespace ContainerVnWFnGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcceuilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Acceuil' shared autowired service.
     *
     * @return \App\Controller\Acceuil
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Acceuil.php';

        $container->services['App\\Controller\\Acceuil'] = $instance = new \App\Controller\Acceuil();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->get_ServiceLocator_JIxfAsiService())->withContext('App\\Controller\\Acceuil', $container));

        return $instance;
    }
}
