controllers:
    resource: ../src/Controller/
    type: attribute

client_prenom:
    path:       /client/prenom/{name}
    controller: App\Controller\client::info
    methods:    GET|HEAD
    requirements:
        name: ^[a-z]+(?:-?[a-z]+)+$

images:
  path: /img/home
  controller: App\Controller\ImagesController::home
  requirements:
    path: .+

images_show:
  path: /img/data/{path}
  controller: App\Controller\ImagesController::show
  requirements:
    path: .+

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: GET|POST
    requirements:
        _locale: en|fr