<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYHKN3ND\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYHKN3ND/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYHKN3ND.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYHKN3ND\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYHKN3ND\App_KernelDevDebugContainer([
    'container.build_hash' => 'YHKN3ND',
    'container.build_id' => '0639cf28',
    'container.build_time' => 1669388152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYHKN3ND');
