<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'kernel_controller' => [[], ['ouverture' => '10/18', '_controller' => 'App\\Controller\\Acceuil::home'], [], [['text', '/test']], [], [], []],
    'image' => [[], ['_controller' => 'App\\Controller\\ImageController::index'], [], [['text', '/']], [], [], []],
    'image_show' => [['img'], ['_controller' => 'App\\Controller\\ImageController::image'], [], [['variable', '/', '[^/]++', 'img', true], ['text', '/images']], [], [], []],
    'client_photo' => [['img'], ['_controller' => 'App\\Controller\\ImageController::imageShow'], [], [['variable', '/', '[^/]++', 'img', true], ['text', '/photo']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], ['_locale' => 'en|fr|de'], [['text', '/login']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\client::index'], [], [['text', '/client']], [], [], []],
    'client_prenom' => [['name'], ['_controller' => 'App\\Controller\\client::info'], ['name' => '[a-z]+(?:-?[a-z]+)+'], [['variable', '/', '[a-z]+(?:-?[a-z]+)+', 'name', true], ['text', '/client/prenom']], [], [], []],
    'images' => [[], ['_controller' => 'App\\Controller\\ImagesController::home'], ['path' => '.+'], [['text', '/img/home']], [], [], []],
    'images_show' => [['path'], ['_controller' => 'App\\Controller\\ImagesController::show'], ['path' => '.+'], [['variable', '/', '.+', 'path', true], ['text', '/img/data']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], ['_locale' => 'en|fr'], [['text', '/login']], [], [], []],
];
